services:
  db:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

    backend:
      build:
        context: ./Backend
      working_dir: /app
      environment:
        DJANGO_DEBUG: ${DJANGO_DEBUG}
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: db
        DB_PORT: 3306
        CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
        DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
        DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
        DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - ./Backend:/app
      ports:
        - "8000:8000"
      command: >
        bash -lc "
          python manage.py migrate &&
          python manage.py shell -c \"import init_superuser\" &&
          python manage.py runserver 0.0.0.0:8000
        "
      restart: unless-stopped
  frontend:
    build:
      context: ./Frontend         
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

volumes:
  dbdata:
  staticfiles:
  media:
